-- ==============================================================================
-- 1. CÁC BẢNG ĐỘC LẬP
-- ==============================================================================
CREATE TABLE APP_ROLE (
    ROLE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_NAME VARCHAR2(100) NOT NULL,
    CAN_ADD NUMBER(1) DEFAULT 0,
    CAN_EDIT NUMBER(1) DEFAULT 0,
    CAN_VIEW NUMBER(1) DEFAULT 0,
    CAN_DELETE NUMBER(1) DEFAULT 0,
    CAN_DOWNLOAD NUMBER(1) DEFAULT 0,
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE APP_USER (
    USER_ID VARCHAR2(50) PRIMARY KEY,
    HOTEN VARCHAR2(255) NOT NULL,
    NGAYSINH DATE,
    SDT VARCHAR2(20),
    DIACHI VARCHAR2(500),
    QUYENHAN VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LOAI_NHAN_VIEN (
    MALNV VARCHAR2(50) PRIMARY KEY,
    VITRI VARCHAR2(255),
    MUCLUONG NUMBER(18, 2),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LOAIKHUVUC (
    MALOAIKV VARCHAR2(50) PRIMARY KEY,
    TENLOAIKV VARCHAR2(255),
    SOLUONG NUMBER,
    GIA NUMBER(18, 2),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE QUA_TANG (
    MAQT VARCHAR2(50) PRIMARY KEY,
    SODIEMTIEUHAO NUMBER,
    NOIDUNG VARCHAR2(500),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CA_LAM (
    MACA VARCHAR2(50) PRIMARY KEY,
    TGBD TIMESTAMP,              
    TGKT TIMESTAMP,            
    NGAYCC DATE,                 -- Ngày chấm công 
    SOGIOLAM NUMBER(5, 2),       
    THOIGIANTANGCA NUMBER(5, 2), 
    TRANGTHAI VARCHAR2(100),     
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NHA_CUNG_CAP (
    MANCC VARCHAR2(50) PRIMARY KEY,
    TENNCC VARCHAR2(255),
    SDT VARCHAR2(20),
    EMAIL VARCHAR2(100),
    DIACHI VARCHAR2(500),
    WEBSITE VARCHAR2(255),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE KHO (
    MAKHO VARCHAR2(50) PRIMARY KEY,
    TENKHO VARCHAR2(255)
);

CREATE TABLE CHUONG_TRINH_KHUYEN_MAI (
    MACTR VARCHAR2(50) PRIMARY KEY,
    TENCTR VARCHAR2(255),
    NGBD DATE,
    NGKT DATE,
    CHIETKHAU NUMBER(5, 2),
    LOAICTR VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SAN_PHAM (
    MASP VARCHAR2(50) PRIMARY KEY,
    TENSP VARCHAR2(255),
    DVT VARCHAR2(50),
    LOAISP VARCHAR2(100),
    SOLUONGTK NUMBER,
    DONGIABQ NUMBER(18, 2),
    SODIEMTICHLUY NUMBER,
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 2. CÁC BẢNG PHỤ THUỘC (CÓ LIÊN KẾT KHÓA NGOẠI)
-- ==============================================================================

CREATE TABLE APP_ACCOUNT (
    ACCOUNT_ID VARCHAR2(50) PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    USERNAME VARCHAR2(100) UNIQUE NOT NULL,
    PASS VARCHAR2(255) NOT NULL,
    TRANGTHAI VARCHAR2(100),
    QUYENHANG VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ACC_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID)
);

CREATE TABLE ACCOUNT_ROLE (
    ACCOUNT_ROLE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID VARCHAR2(50) NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ACCR_ACC FOREIGN KEY (ACCOUNT_ID) REFERENCES APP_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT FK_ACCR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLE(ROLE_ID)
);

CREATE TABLE KHACHHANG (
    MAKH VARCHAR2(50) PRIMARY KEY,
    USER_ID VARCHAR2(50), 
    SODT VARCHAR2(20),
    SODIEMTICHLUY NUMBER DEFAULT 0,
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_KH_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID)
);

CREATE TABLE NHAN_VIEN (
    MANV VARCHAR2(50) PRIMARY KEY,
    USER_ID VARCHAR2(50),
    MALNV VARCHAR2(50),
    LUONG_CB NUMBER(18, 2),
    TRANGTHAI VARCHAR2(100),
    NGAYVAOLAM DATE,
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_NV_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID),
    CONSTRAINT FK_NV_LNV FOREIGN KEY (MALNV) REFERENCES LOAI_NHAN_VIEN(MALNV)
);

CREATE TABLE CHI_TIET_CA_LAM (
    MANV VARCHAR2(50),
    MACA VARCHAR2(50),
    TRANGTHAI VARCHAR2(100),
    PRIMARY KEY (MANV, MACA),
    CONSTRAINT FK_CTCL_NV FOREIGN KEY (MANV) REFERENCES NHAN_VIEN(MANV),
    CONSTRAINT FK_CTCL_CA FOREIGN KEY (MACA) REFERENCES CA_LAM(MACA)
);

CREATE TABLE KHUVUC (
    MAKV VARCHAR2(50) PRIMARY KEY,
    MALOAIKV VARCHAR2(50) NOT NULL,
    TENKV VARCHAR2(255),
    SOMAYKV NUMBER,
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_KV_LKV FOREIGN KEY (MALOAIKV) REFERENCES LOAIKHUVUC(MALOAIKV)
);

CREATE TABLE PC (
    MAPC VARCHAR2(50) PRIMARY KEY,
    MAKV VARCHAR2(50),
    CPU VARCHAR2(100),
    RAM VARCHAR2(100),
    VGA VARCHAR2(100),
    ROM VARCHAR2(100),
    SOMAY NUMBER,
    LOAIPC VARCHAR2(100),
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PC_KV FOREIGN KEY (MAKV) REFERENCES KHUVUC(MAKV)
);

CREATE TABLE LICHSUCHOI (
    MALS VARCHAR2(50) PRIMARY KEY,
    MAPC VARCHAR2(50),
    MAKH VARCHAR2(50),
    NGAYBD TIMESTAMP,
    NGAYKT TIMESTAMP,
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LSC_PC FOREIGN KEY (MAPC) REFERENCES PC(MAPC),
    CONSTRAINT FK_LSC_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

CREATE TABLE PHIEU_THANH_TOAN (
    MAPTT VARCHAR2(50) PRIMARY KEY,
    MALS VARCHAR2(50),
    TONGTIEN NUMBER(18, 2),
    TONGTHOIGIAN NUMBER,
    TONGSODV NUMBER ,
    TONGTIENDV NUMBER(18, 2),
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PTT_LSC FOREIGN KEY (MALS) REFERENCES LICHSUCHOI(MALS)
);

CREATE TABLE LICHSUDOIQUA (
    MADQ VARCHAR2(50) PRIMARY KEY,
    MAKH VARCHAR2(50),
    MAQT VARCHAR2(50),
    SL NUMBER,
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LSDQ_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_LSDQ_QT FOREIGN KEY (MAQT) REFERENCES QUA_TANG(MAQT)
);

CREATE TABLE KHUYEN_MAI_SAN_PHAM (
    MAKMSP VARCHAR2(50) PRIMARY KEY,
    MASP VARCHAR2(50),
    MACTR VARCHAR2(50),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_KMSP_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP),
    CONSTRAINT FK_KMSP_CTR FOREIGN KEY (MACTR) REFERENCES CHUONG_TRINH_KHUYEN_MAI(MACTR)
);

CREATE TABLE DICH_VU_DA_DUNG (
    MADVDD VARCHAR2(50) PRIMARY KEY,
    MALS VARCHAR2(50),
    MASP VARCHAR2(50),
    SL NUMBER,
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_DVDD_LSC FOREIGN KEY (MALS) REFERENCES LICHSUCHOI(MALS),
    CONSTRAINT FK_DVDD_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP)
);

CREATE TABLE PHIEU_NHAP_KHO (
    MAPNK VARCHAR2(50) PRIMARY KEY,
    MAKHO VARCHAR2(50),
    MANV VARCHAR2(50),
    NGAYNHAP DATE,
    TONGTIENNHAP NUMBER(18, 2),
    CONSTRAINT FK_PNK_KHO FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO),
    CONSTRAINT FK_PNK_NV FOREIGN KEY (MANV) REFERENCES NHAN_VIEN(MANV)
);

CREATE TABLE CHI_TIET_NHAP_KHO (
    MAPNK VARCHAR2(50),
    MASP VARCHAR2(50),
    LOAIHANG VARCHAR2(100),
    SOLUONGNHAP NUMBER,
    GIANHAP NUMBER(18, 2),
    PRIMARY KEY (MAPNK, MASP),
    CONSTRAINT FK_CTNK_PNK FOREIGN KEY (MAPNK) REFERENCES PHIEU_NHAP_KHO(MAPNK) ON DELETE CASCADE,
    CONSTRAINT FK_CTNK_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP)
);

CREATE TABLE THIET_BI (
    MATB VARCHAR2(50) PRIMARY KEY,
    MAPC VARCHAR2(50),
    TENTB VARCHAR2(255),
    LOAITB VARCHAR2(100),
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TB_PC FOREIGN KEY (MAPC) REFERENCES PC(MAPC)
);

CREATE TABLE NHAP_HANG (
    MANH VARCHAR2(50) PRIMARY KEY,
    MANCC VARCHAR2(50),
    TRIGIA NUMBER(18, 2),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_NH_NCC FOREIGN KEY (MANCC) REFERENCES NHA_CUNG_CAP(MANCC)
);

CREATE TABLE CHI_TIET_NHAP_HANG (
    MANH VARCHAR2(50),
    MASP VARCHAR2(50),
    SLTHEOCHUNGTU NUMBER NOT NULL,  
    SLTHUCNHAP NUMBER NOT NULL,      
    DONGIA NUMBER(18, 2) NOT NULL,
    CHIPHIKHAC NUMBER(18, 2) DEFAULT 0,
    VAT NUMBER(5, 2) DEFAULT 0,
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MANH, MASP),
    CONSTRAINT FK_CTNH_NH FOREIGN KEY (MANH) REFERENCES NHAP_HANG(MANH),
    CONSTRAINT FK_CTNH_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP)
);

CREATE TABLE CTNHAPTHIETBI (
    MACTNTB VARCHAR2(50) PRIMARY KEY,
    MANH VARCHAR2(50),
    MATB VARCHAR2(50),
    DONGIA NUMBER(18, 2),
    SL NUMBER,
    VAT NUMBER(5, 2),
    CHIPHIKHAC NUMBER(18, 2),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CTNTB_NH FOREIGN KEY (MANH) REFERENCES NHAP_HANG(MANH),
    CONSTRAINT FK_CTNTB_TB FOREIGN KEY (MATB) REFERENCES THIET_BI(MATB)
);

CREATE TABLE THAYTHETHIETBI (
    MATTTB VARCHAR2(50) PRIMARY KEY,
    MATB VARCHAR2(50),
    MAPC VARCHAR2(50),
    MANV VARCHAR2(50),
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TTTB_TB FOREIGN KEY (MATB) REFERENCES THIET_BI(MATB),
    CONSTRAINT FK_TTTB_PC FOREIGN KEY (MAPC) REFERENCES PC(MAPC),
    CONSTRAINT FK_TTTB_NV FOREIGN KEY (MANV) REFERENCES NHAN_VIEN(MANV)
);


-- ==========================================================
-- RBTV - 1. RÀNG BUỘC MIỀN GIÁ TRỊ (DOMAIN CONSTRAINTS)
-- ==========================================================
-- Các trường Boolean (IS_DELETE, CAN_ADD...) chỉ nhận 0 hoặc 1
ALTER TABLE APP_ROLE ADD CONSTRAINT CHK_ROLE_CAN_ADD CHECK (CAN_ADD IN (0, 1));
ALTER TABLE APP_ROLE ADD CONSTRAINT CHK_ROLE_CAN_EDIT CHECK (CAN_EDIT IN (0, 1));
ALTER TABLE APP_ROLE ADD CONSTRAINT CHK_ROLE_CAN_VIEW CHECK (CAN_VIEW IN (0, 1));
ALTER TABLE APP_ROLE ADD CONSTRAINT CHK_ROLE_CAN_DELETE CHECK (CAN_DELETE IN (0, 1));
ALTER TABLE APP_ROLE ADD CONSTRAINT CHK_ROLE_CAN_DOWNLOAD CHECK (CAN_DOWNLOAD IN (0, 1));
ALTER TABLE APP_ROLE ADD CONSTRAINT CHK_ROLE_IS_DELETE CHECK (IS_DELETE IN (0, 1));

ALTER TABLE APP_USER ADD CONSTRAINT CHK_USER_IS_DELETE CHECK (IS_DELETE IN (0, 1));
ALTER TABLE APP_ACCOUNT ADD CONSTRAINT CHK_ACC_IS_DELETE CHECK (IS_DELETE IN (0, 1));

-- Các trường số lượng, tiền tệ, điểm số phải lớn hơn hoặc bằng 0
ALTER TABLE LOAI_NHAN_VIEN ADD CONSTRAINT CHK_LNV_MUCLUONG CHECK (MUCLUONG >= 0);
ALTER TABLE LOAIKHUVUC ADD CONSTRAINT CHK_LKV_SOLUONG CHECK (SOLUONG >= 0);
ALTER TABLE LOAIKHUVUC ADD CONSTRAINT CHK_LKV_GIA CHECK (GIA >= 0);

ALTER TABLE QUA_TANG ADD CONSTRAINT CHK_QT_SODIEMTIEUHAO CHECK (SODIEMTIEUHAO > 0);
ALTER TABLE CA_LAM ADD CONSTRAINT CHK_CA_SOGIOLAM CHECK (SOGIOLAM >= 0);
ALTER TABLE CA_LAM ADD CONSTRAINT CHK_CA_TGTANGCA CHECK (THOIGIANTANGCA >= 0);

ALTER TABLE CHUONG_TRINH_KHUYEN_MAI ADD CONSTRAINT CHK_CTKM_CHIETKHAU CHECK (CHIETKHAU >= 0 AND CHIETKHAU <= 100);

ALTER TABLE SAN_PHAM ADD CONSTRAINT CHK_SP_SOLUONGTK CHECK (SOLUONGTK >= 0);
ALTER TABLE SAN_PHAM ADD CONSTRAINT CHK_SP_DONGIABQ CHECK (DONGIABQ >= 0);
ALTER TABLE SAN_PHAM ADD CONSTRAINT CHK_SP_DIEM CHECK (SODIEMTICHLUY >= 0);

ALTER TABLE KHACHHANG ADD CONSTRAINT CHK_KH_DIEM CHECK (SODIEMTICHLUY >= 0);
ALTER TABLE NHAN_VIEN ADD CONSTRAINT CHK_NV_LUONG CHECK (LUONG_CB >= 0);

ALTER TABLE PHIEU_THANH_TOAN ADD CONSTRAINT CHK_PTT_TONGTIEN CHECK (TONGTIEN >= 0);
ALTER TABLE PHIEU_THANH_TOAN ADD CONSTRAINT CHK_PTT_TONGTIENDV CHECK (TONGTIENDV >= 0);
ALTER TABLE PHIEU_THANH_TOAN ADD CONSTRAINT CHK_PTT_TONGTHOIGIAN CHECK (TONGTHOIGIAN >= 0);

-- Kiểm tra ngày hợp lệ (Không được lớn hơn ngày hiện tại)
ALTER TABLE APP_USER ADD CONSTRAINT CHK_USER_NGAYSINH CHECK (NGAYSINH <= SYSDATE);
ALTER TABLE NHAN_VIEN ADD CONSTRAINT CHK_NV_NGAYVAOLAM CHECK (NGAYVAOLAM <= SYSDATE);


-- ==========================================================
-- RBTV - 2. RÀNG BUỘC LIÊN THUỘC TÍNH (INTRA-RELATION)
-- ==========================================================
-- Thời gian kết thúc phải lớn hơn thời gian bắt đầu
ALTER TABLE CA_LAM ADD CONSTRAINT CHK_CA_THOIGIAN CHECK (TGBD < TGKT);
ALTER TABLE CHUONG_TRINH_KHUYEN_MAI ADD CONSTRAINT CHK_CTKM_NGAY CHECK (NGBD <= NGKT);
ALTER TABLE LICHSUCHOI ADD CONSTRAINT CHK_LSC_THOIGIAN CHECK (NGAYBD <= NGAYKT);


-- ==========================================================
-- TRIGGER 
-- ==========================================================
-- 1. Tự động tính Tổng Tiền Nhập Kho khi thêm Chi tiết nhập kho
CREATE OR REPLACE TRIGGER TRG_TINH_TONGTIEN_NHAPKHO
AFTER INSERT OR UPDATE ON CHI_TIET_NHAP_KHO
FOR EACH ROW
BEGIN
    UPDATE PHIEU_NHAP_KHO
    SET TONGTIENNHAP = NVL(TONGTIENNHAP, 0) + (:NEW.SOLUONGNHAP * :NEW.GIANHAP) + NVL(:NEW.CHIPHIKHAC, 0)
    WHERE MAPNK = :NEW.MAPNK;
END;
/

-- 2. Tự động tính Tổng Tiền Dịch Vụ khi khách gọi món
CREATE OR REPLACE TRIGGER TRG_TINH_TIEN_DICHVU
AFTER INSERT OR UPDATE ON DICH_VU_DA_DUNG
FOR EACH ROW
DECLARE
    v_dongia SAN_PHAM.DONGIABQ%TYPE;
BEGIN
    -- Lấy đơn giá của sản phẩm được gọi
    SELECT DONGIABQ INTO v_dongia FROM SAN_PHAM WHERE MASP = :NEW.MASP;
    
    -- Cộng dồn vào TONGTIENDV và TONGTIEN của Phieu_Thanh_Toan
    UPDATE PHIEU_THANH_TOAN
    SET TONGSODV = NVL(TONGSODV, 0) + :NEW.SL,
        TONGTIENDV = NVL(TONGTIENDV, 0) + (:NEW.SL * v_dongia),
        TONGTIEN = NVL(TONGTIEN, 0) + (:NEW.SL * v_dongia)
    WHERE MALS = :NEW.MALS;
END;
/

-- 3. Đảm bảo Số máy của khu vực (SOMAYKV) khớp với số lượng PC thực tế
CREATE OR REPLACE TRIGGER TRG_CAPNHAT_SOMAY_KHUVUC
AFTER INSERT OR DELETE ON PC
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE KHUVUC SET SOMAYKV = NVL(SOMAYKV, 0) + 1 WHERE MAKV = :NEW.MAKV;
    ELSIF DELETING THEN
        UPDATE KHUVUC SET SOMAYKV = SOMAYKV - 1 WHERE MAKV = :OLD.MAKV;
    END IF;
END;
/

-- Trigger cập nhật tồn kho khi nhập hàng
CREATE OR REPLACE TRIGGER trg_CapNhatTonKho_NhapHang
AFTER INSERT ON CHI_TIET_NHAP_KHO
FOR EACH ROW
DECLARE
    v_soluongtk_hientai SAN_PHAM.SOLUONGTK%TYPE;
    v_tensp             SAN_PHAM.TENSP%TYPE;
BEGIN
    SELECT SOLUONGTK, TENSP 
    INTO v_soluongtk_hientai, v_tensp
    FROM SAN_PHAM
    WHERE MASP = :NEW.MASP;

    IF :NEW.SOLUONGNHAP <= 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 
            'Loi: So luong nhap cho san pham [' || v_tensp || '] phai lon hon 0! ' ||
            '(So luong nhap hien tai: ' || :NEW.SOLUONGNHAP || ')');
    END IF;

    UPDATE SAN_PHAM
    SET SOLUONGTK = v_soluongtk_hientai + :NEW.SOLUONGNHAP
    WHERE MASP = :NEW.MASP;
END;
/

-- Trigger trừ tồn kho khi khách sử dụng dịch vụ (Bán hàng)
CREATE OR REPLACE TRIGGER trg_CapNhatTonKho_BanHang
AFTER INSERT ON DICH_VU_DA_DUNG
FOR EACH ROW
DECLARE
    v_soluongtk SAN_PHAM.SOLUONGTK%TYPE;
BEGIN
    SELECT SOLUONGTK INTO v_soluongtk 
    FROM SAN_PHAM 
    WHERE MASP = :NEW.MASP;

    IF v_soluongtk < :NEW.SL THEN
        RAISE_APPLICATION_ERROR(-20002, 'Lỗi: Số lượng tồn kho không đủ để đáp ứng yêu cầu!');
    ELSE
        UPDATE SAN_PHAM
        SET SOLUONGTK = SOLUONGTK - :NEW.SL
        WHERE MASP = :NEW.MASP;
    END IF;
END;
/

-- Trigger cộng điểm tích lũy khi nạp tiền/thanh toán
CREATE OR REPLACE TRIGGER trg_CapNhatDiem_ThanhToan
AFTER INSERT ON PHIEU_THANH_TOAN
FOR EACH ROW
DECLARE
    v_makh KHACHHANG.MAKH%TYPE;
BEGIN
    BEGIN
        SELECT MAKH INTO v_makh
        FROM LICHSUCHOI
        WHERE MALS = :NEW.MALS;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_makh := NULL; 
    END;

    -- quy đổi: 1,000 VNĐ = 1 điểm tích lũy
    IF v_makh IS NOT NULL THEN
        UPDATE KHACHHANG
        SET SODIEMTICHLUY = NVL(SODIEMTICHLUY, 0) + FLOOR(NVL(:NEW.TONGTIEN, 0) / 1000)
        WHERE MAKH = v_makh;
    END IF;
END;
/

-- Trigger trừ điểm khi đổi quà
CREATE OR REPLACE TRIGGER trg_TruDiem_DoiQua
AFTER INSERT ON LICHSUDOIQUA
FOR EACH ROW
DECLARE
    v_diemtieuhao QUA_TANG.SODIEMTIEUHAO%TYPE;
    v_diemhientai KHACHHANG.SODIEMTICHLUY%TYPE;
BEGIN
    SELECT SODIEMTIEUHAO INTO v_diemtieuhao 
    FROM QUA_TANG 
    WHERE MAQT = :NEW.MAQT;

    SELECT SODIEMTICHLUY INTO v_diemhientai 
    FROM KHACHHANG 
    WHERE MAKH = :NEW.MAKH;

    IF NVL(v_diemhientai, 0) < (v_diemtieuhao * :NEW.SL) THEN
        RAISE_APPLICATION_ERROR(-20003, 'Lỗi: Khách hàng không đủ điểm tích lũy để đổi quà!');
    ELSE
        UPDATE KHACHHANG
        SET SODIEMTICHLUY = SODIEMTICHLUY - (v_diemtieuhao * :NEW.SL)
        WHERE MAKH = :NEW.MAKH;
    END IF;
END;
/

-- Trigger cập nhật trạng thái thiết bị khi thay thế
CREATE OR REPLACE TRIGGER trg_CapNhatTrangThai_ThayTheThietBi
AFTER INSERT ON THAYTHETHIETBI
FOR EACH ROW
BEGIN
    UPDATE THIET_BI
    SET TRANGTHAI = 'Hong/Da thao'
    WHERE MATB = :NEW.MATB;
END;
/


-- ==========================================================
-- PROCEDURE
-- ==========================================================
-- Procedure thêm phiếu thanh toán mới
CREATE OR REPLACE PROCEDURE INSERT_PHIEU_THANH_TOAN (
    PAR_MALS          PHIEU_THANH_TOAN.MALS%TYPE,
    PAR_TONGTIEN      PHIEU_THANH_TOAN.TONGTIEN%TYPE,
    PAR_TONGTHOIGIAN  PHIEU_THANH_TOAN.TONGTHOIGIAN%TYPE,
    PAR_TONGSODV     PHIEU_THANH_TOAN.TONGSODV%TYPE,
    PAR_TONGTIENDV    PHIEU_THANH_TOAN.TONGTIENDV%TYPE,
    PAR_TRANGTHAI     PHIEU_THANH_TOAN.TRANGTHAI%TYPE,
    MAPTT_OUT     OUT PHIEU_THANH_TOAN.MAPTT%TYPE
)
AS
    VAR_NEW_MAPTT VARCHAR2(50);
BEGIN
    -- Tạo mã phiếu thanh toán tự động
    VAR_NEW_MAPTT := 'PTT_' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '_' || TO_CHAR(SYS_GUID());

    INSERT INTO PHIEU_THANH_TOAN (MAPTT, MALS, TONGTIEN, TONGTHOIGIAN, TONGSODV, TONGTIENDV, TRANGTHAI)
    VALUES (VAR_NEW_MAPTT, PAR_MALS, PAR_TONGTIEN, PAR_TONGTHOIGIAN, PAR_TONGSODV, PAR_TONGTIENDV, PAR_TRANGTHAI)
    RETURNING MAPTT INTO MAPTT_OUT;
    COMMIT;

    UPDATE LICHSUCHOI
    SET TRANGTHAI = 'Da thanh toan',
        NGAYKT = CURRENT_TIMESTAMP
    WHERE MALS = PAR_MALS;
    COMMIT;
END;
/

-- Procedure tạo mới phiên chơi 
CREATE OR REPLACE PROCEDURE INSERT_LICHSUCHOI (
    PAR_MAPC        LICHSUCHOI.MAPC%TYPE,
    PAR_MAKH        LICHSUCHOI.MAKH%TYPE,
    PAR_TRANGTHAI   LICHSUCHOI.TRANGTHAI%TYPE,
    MALS_OUT    OUT LICHSUCHOI.MALS%TYPE
)
AS
    VAR_NEW_MALS VARCHAR2(50);
BEGIN
    VAR_NEW_MALS := 'LSC_' || TO_CHAR(SYS_GUID());
    INSERT INTO LICHSUCHOI (MALS, MAPC, MAKH, NGAYBD, NGAYKT, TRANGTHAI)
    VALUES (VAR_NEW_MALS, PAR_MAPC, PAR_MAKH, CURRENT_TIMESTAMP, NULL, PAR_TRANGTHAI)
    RETURNING MALS INTO MALS_OUT;
    COMMIT;
END;
/

-- Procedure cập nhật điểm tích lũy
CREATE OR REPLACE PROCEDURE CONG_DIEM_TICHLUY (
    PAR_MAKH KHACHHANG.MAKH%TYPE,
    PAR_DIEM_CONG NUMBER
)
AS
    VAR_DIEM_HIENTAI NUMBER;
BEGIN
    SELECT SODIEMTICHLUY INTO VAR_DIEM_HIENTAI
    FROM KHACHHANG
    WHERE MAKH = PAR_MAKH;
    
    DBMS_SESSION.SLEEP(5);    
    UPDATE KHACHHANG
    SET SODIEMTICHLUY = VAR_DIEM_HIENTAI + PAR_DIEM_CONG
    WHERE MAKH = PAR_MAKH;
    COMMIT;
END;
/

-- Procedure cập nhật điểm tích lũy (Trừ điểm khi đổi quà): 
CREATE OR REPLACE PROCEDURE TRU_DIEM_DOIQUA (
    PAR_MAKH KHACHHANG.MAKH%TYPE,
    PAR_DIEM_TRU NUMBER
)
AS
    VAR_DIEM_HIENTAI NUMBER;
BEGIN
    SELECT SODIEMTICHLUY INTO VAR_DIEM_HIENTAI
    FROM KHACHHANG
    WHERE MAKH = PAR_MAKH;
    
    UPDATE KHACHHANG
    SET SODIEMTICHLUY = VAR_DIEM_HIENTAI - PAR_DIEM_TRU
    WHERE MAKH = PAR_MAKH;
    COMMIT;
END;
/

-- Procedure Thay thế thiết bị 
CREATE OR REPLACE PROCEDURE THAY_THE_THIET_BI_PC (
    PAR_MATB VARCHAR2,
    PAR_MAPC VARCHAR2
) AS
BEGIN
    UPDATE THIET_BI 
    SET TRANGTHAI = 'Da thay the' 
    WHERE MATB = PAR_MATB;
    
    DBMS_SESSION.SLEEP(5); -- Giả lập độ trễ xử lý
    
    UPDATE PC 
    SET TRANGTHAI = 'Hoat dong' 
    WHERE MAPC = PAR_MAPC;
    COMMIT;
END; 
/

-- Procedure Bảo trì máy trạm 
CREATE OR REPLACE PROCEDURE BAO_TRI_MAY_TRAM (
    PAR_MAPC VARCHAR2,
    PAR_MATB VARCHAR2
) AS
BEGIN
    UPDATE PC 
    SET TRANGTHAI = 'Bao tri' 
    WHERE MAPC = PAR_MAPC;
    
    DBMS_SESSION.SLEEP(5); -- Giả lập độ trễ xử lý
    
    UPDATE THIET_BI 
    SET TRANGTHAI = 'Bao tri' 
    WHERE MATB = PAR_MATB;
    COMMIT;
END;
/

-- Procedure cập nhật đơn giá sản phẩm 
CREATE OR REPLACE PROCEDURE CAPNHAT_GIA_SANPHAM (
    PAR_MASP VARCHAR2,
    PAR_GIA_MOI NUMBER
) AS
BEGIN
    UPDATE SAN_PHAM
    SET DONGIABQ = PAR_GIA_MOI
    WHERE MASP = PAR_MASP;
    COMMIT;
END;
/