-- ==============================================================================
-- 1. CÁC BẢNG ĐỘC LẬP & BẢNG LOG HỆ THỐNG
-- ==============================================================================
CREATE TABLE SYSTEM_ERROR_LOG (
    LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROCEDURE_NAME VARCHAR2(100),
    ERROR_CODE NUMBER,
    ERROR_MESSAGE VARCHAR2(1000),
    LOG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE APP_ROLE (
    ROLE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_NAME VARCHAR2(100) NOT NULL,
    CAN_ADD NUMBER(1) DEFAULT 0,
    CAN_EDIT NUMBER(1) DEFAULT 0,
    CAN_VIEW NUMBER(1) DEFAULT 0,
    CAN_DELETE NUMBER(1) DEFAULT 0,
    CAN_DOWNLOAD NUMBER(1) DEFAULT 0,
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE APP_USER (
    USER_ID VARCHAR2(50) PRIMARY KEY,
    HOTEN VARCHAR2(255) NOT NULL,
    NGAYSINH DATE,
    SDT VARCHAR2(20),
    DIACHI VARCHAR2(500),
    QUYENHAN VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LOAI_NHAN_VIEN (
    MALNV VARCHAR2(50) PRIMARY KEY,
    VITRI VARCHAR2(255),
    MUCLUONG NUMBER(18, 2),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LOAIKHUVUC (
    MALOAIKV VARCHAR2(50) PRIMARY KEY,
    TENLOAIKV VARCHAR2(255),
    SOLUONG NUMBER,
    GIA NUMBER(18, 2),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE QUA_TANG (
    MAQT VARCHAR2(50) PRIMARY KEY,
    SODIEMTIEUHAO NUMBER,
    NOIDUNG VARCHAR2(500),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CA_LAM (
    MACA VARCHAR2(50) PRIMARY KEY,
    TGBD TIMESTAMP,              
    TGKT TIMESTAMP,            
    NGAYCC DATE,                 
    SOGIOLAM NUMBER(5, 2),       
    THOIGIANTANGCA NUMBER(5, 2), 
    TRANGTHAI VARCHAR2(100),     
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NHA_CUNG_CAP (
    MANCC VARCHAR2(50) PRIMARY KEY,
    TENNCC VARCHAR2(255),
    SDT VARCHAR2(20),
    EMAIL VARCHAR2(100),
    DIACHI VARCHAR2(500),
    WEBSITE VARCHAR2(255),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE KHO (
    MAKHO VARCHAR2(50) PRIMARY KEY,
    TENKHO VARCHAR2(255)
);

CREATE TABLE CHUONG_TRINH_KHUYEN_MAI (
    MACTR VARCHAR2(50) PRIMARY KEY,
    TENCTR VARCHAR2(255),
    NGBD DATE,
    NGKT DATE,
    CHIETKHAU NUMBER(5, 2),
    LOAICTR VARCHAR2(100),
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SAN_PHAM (
    MASP VARCHAR2(50) PRIMARY KEY,
    TENSP VARCHAR2(255),
    DVT VARCHAR2(50),
    LOAISP VARCHAR2(100),
    SOLUONGTK NUMBER,
    DONGIABQ NUMBER(18, 2),
    SODIEMTICHLUY NUMBER,
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 2. CÁC BẢNG PHỤ THUỘC (CÓ LIÊN KẾT KHÓA NGOẠI)
-- ==============================================================================

CREATE TABLE APP_ACCOUNT (
    ACCOUNT_ID VARCHAR2(50) PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    USERNAME VARCHAR2(100) UNIQUE NOT NULL,
    PASS VARCHAR2(255) NOT NULL,
    TRANGTHAI VARCHAR2(100),
    QUYENHANG VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ACC_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID)
);

CREATE TABLE ACCOUNT_ROLE (
    ACCOUNT_ROLE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID VARCHAR2(50) NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ACCR_ACC FOREIGN KEY (ACCOUNT_ID) REFERENCES APP_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT FK_ACCR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLE(ROLE_ID)
);

CREATE TABLE KHACHHANG (
    MAKH VARCHAR2(50) PRIMARY KEY,
    USER_ID VARCHAR2(50), 
    SODT VARCHAR2(20),
    SODIEMTICHLUY NUMBER DEFAULT 0,
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_KH_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID)
);
ALTER TABLE KHACHHANG ADD SODU NUMBER(18, 2) DEFAULT 0;
ALTER TABLE KHACHHANG ADD CONSTRAINT CHK_KH_SODU CHECK (SODU >= 0);

CREATE TABLE PHIEUNAPTIEN (
    MAPN VARCHAR2(50) PRIMARY KEY,
    MAKH VARCHAR2(50) NOT NULL,
    SOTIEN NUMBER(18, 2) NOT NULL,
    DIEMCONG NUMBER DEFAULT 0,
    NGAYNAP DATE DEFAULT SYSDATE,
    CONSTRAINT FK_PN_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

CREATE TABLE NHAN_VIEN (
    MANV VARCHAR2(50) PRIMARY KEY,
    USER_ID VARCHAR2(50),
    MALNV VARCHAR2(50),
    LUONG_CB NUMBER(18, 2),
    TRANGTHAI VARCHAR2(100),
    NGAYVAOLAM DATE,
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_NV_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID),
    CONSTRAINT FK_NV_LNV FOREIGN KEY (MALNV) REFERENCES LOAI_NHAN_VIEN(MALNV)
);
ALTER TABLE  NHAN_VIEN ADD NGAYTHOIVIEC DATE ; 
ALTER TABLE NHAN_VIEN ADD SOBHYT VARCHAR2(50) ;
ALTER TABLE NHAN_VIEN ADD MASOTHUECN VARCHAR2(50) ;

CREATE TABLE CHI_TIET_CA_LAM (
    MANV VARCHAR2(50),
    MACA VARCHAR2(50),
    TRANGTHAI VARCHAR2(100),
    PRIMARY KEY (MANV, MACA),
    CONSTRAINT FK_CTCL_NV FOREIGN KEY (MANV) REFERENCES NHAN_VIEN(MANV),
    CONSTRAINT FK_CTCL_CA FOREIGN KEY (MACA) REFERENCES CA_LAM(MACA)
);

CREATE TABLE KHUVUC (
    MAKV VARCHAR2(50) PRIMARY KEY,
    MALOAIKV VARCHAR2(50) NOT NULL,
    TENKV VARCHAR2(255),
    SOMAYKV NUMBER,
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_KV_LKV FOREIGN KEY (MALOAIKV) REFERENCES LOAIKHUVUC(MALOAIKV)
);

CREATE TABLE PC (
    MAPC VARCHAR2(50) PRIMARY KEY,
    MAKV VARCHAR2(50),
    CPU VARCHAR2(100),
    RAM VARCHAR2(100),
    VGA VARCHAR2(100),
    ROM VARCHAR2(100),
    SOMAY NUMBER,
    LOAIPC VARCHAR2(100),
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PC_KV FOREIGN KEY (MAKV) REFERENCES KHUVUC(MAKV)
);

CREATE TABLE LICHSUCHOI (
    MALS VARCHAR2(50) PRIMARY KEY,
    MAPC VARCHAR2(50),
    MAKH VARCHAR2(50),
    NGAYBD TIMESTAMP,
    NGAYKT TIMESTAMP,
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LSC_PC FOREIGN KEY (MAPC) REFERENCES PC(MAPC),
    CONSTRAINT FK_LSC_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

CREATE TABLE PHIEU_THANH_TOAN (
    MAPTT VARCHAR2(50) PRIMARY KEY,
    MALS VARCHAR2(50),
    TONGTIEN NUMBER(18, 2),
    TONGTHOIGIAN NUMBER,
    TONGSODV NUMBER ,
    TONGTIENDV NUMBER(18, 2),
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PTT_LSC FOREIGN KEY (MALS) REFERENCES LICHSUCHOI(MALS)
);

CREATE TABLE LICHSUDOIQUA (
    MADQ VARCHAR2(50) PRIMARY KEY,
    MAKH VARCHAR2(50),
    MAQT VARCHAR2(50),
    SL NUMBER,
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LSDQ_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_LSDQ_QT FOREIGN KEY (MAQT) REFERENCES QUA_TANG(MAQT)
);

CREATE TABLE KHUYEN_MAI_SAN_PHAM (
    MAKMSP VARCHAR2(50) PRIMARY KEY,
    MASP VARCHAR2(50),
    MACTR VARCHAR2(50),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_KMSP_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP),
    CONSTRAINT FK_KMSP_CTR FOREIGN KEY (MACTR) REFERENCES CHUONG_TRINH_KHUYEN_MAI(MACTR)
);

CREATE TABLE DICH_VU_DA_DUNG (
    MADVDD VARCHAR2(50) PRIMARY KEY,
    MALS VARCHAR2(50),
    MASP VARCHAR2(50),
    SL NUMBER,
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_DVDD_LSC FOREIGN KEY (MALS) REFERENCES LICHSUCHOI(MALS),
    CONSTRAINT FK_DVDD_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP)
);

CREATE TABLE PHIEU_NHAP_KHO (
    MAPNK VARCHAR2(50) PRIMARY KEY,
    MAKHO VARCHAR2(50),
    MANV VARCHAR2(50),
    NGAYNHAP DATE,
    TONGTIENNHAP NUMBER(18, 2),
    CONSTRAINT FK_PNK_KHO FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO),
    CONSTRAINT FK_PNK_NV FOREIGN KEY (MANV) REFERENCES NHAN_VIEN(MANV)
);

CREATE TABLE CHI_TIET_NHAP_KHO (
    MAPNK VARCHAR2(50),
    MASP VARCHAR2(50),
    LOAIHANG VARCHAR2(100),
    SOLUONGNHAP NUMBER,
    GIANHAP NUMBER(18, 2),
    PRIMARY KEY (MAPNK, MASP),
    CONSTRAINT FK_CTNK_PNK FOREIGN KEY (MAPNK) REFERENCES PHIEU_NHAP_KHO(MAPNK) ON DELETE CASCADE,
    CONSTRAINT FK_CTNK_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP)
);

CREATE TABLE THIET_BI (
    MATB VARCHAR2(50) PRIMARY KEY,
    MAPC VARCHAR2(50),
    TENTB VARCHAR2(255),
    LOAITB VARCHAR2(100),
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TB_PC FOREIGN KEY (MAPC) REFERENCES PC(MAPC)
);

CREATE TABLE NHAP_HANG (
    MANH VARCHAR2(50) PRIMARY KEY,
    MANCC VARCHAR2(50),
    TRIGIA NUMBER(18, 2),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_NH_NCC FOREIGN KEY (MANCC) REFERENCES NHA_CUNG_CAP(MANCC)
);

CREATE TABLE CHI_TIET_NHAP_HANG (
    MANH VARCHAR2(50),
    MASP VARCHAR2(50),
    SLTHEOCHUNGTU NUMBER NOT NULL,  
    SLTHUCNHAP NUMBER NOT NULL,      
    DONGIA NUMBER(18, 2) NOT NULL,
    CHIPHIKHAC NUMBER(18, 2) DEFAULT 0,
    VAT NUMBER(5, 2) DEFAULT 0,
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MANH, MASP),
    CONSTRAINT FK_CTNH_NH FOREIGN KEY (MANH) REFERENCES NHAP_HANG(MANH),
    CONSTRAINT FK_CTNH_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP)
);

CREATE TABLE CTNHAPTHIETBI (
    MACTNTB VARCHAR2(50) PRIMARY KEY,
    MANH VARCHAR2(50),
    MATB VARCHAR2(50),
    DONGIA NUMBER(18, 2),
    SL NUMBER,
    VAT NUMBER(5, 2),
    CHIPHIKHAC NUMBER(18, 2),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CTNTB_NH FOREIGN KEY (MANH) REFERENCES NHAP_HANG(MANH),
    CONSTRAINT FK_CTNTB_TB FOREIGN KEY (MATB) REFERENCES THIET_BI(MATB)
);

CREATE TABLE THAYTHETHIETBI (
    MATTTB VARCHAR2(50) PRIMARY KEY,
    MATB VARCHAR2(50),
    MAPC VARCHAR2(50),
    MANV VARCHAR2(50),
    TRANGTHAI VARCHAR2(100),
    IS_DELETE NUMBER(1) DEFAULT 0,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TTTB_TB FOREIGN KEY (MATB) REFERENCES THIET_BI(MATB),
    CONSTRAINT FK_TTTB_PC FOREIGN KEY (MAPC) REFERENCES PC(MAPC),
    CONSTRAINT FK_TTTB_NV FOREIGN KEY (MANV) REFERENCES NHAN_VIEN(MANV)
);


-- ==========================================================
-- RBTV - 1. RÀNG BUỘC MIỀN GIÁ TRỊ (DOMAIN CONSTRAINTS)
-- ==========================================================
ALTER TABLE APP_ROLE ADD CONSTRAINT CHK_ROLE_CAN_ADD CHECK (CAN_ADD IN (0, 1));
ALTER TABLE APP_ROLE ADD CONSTRAINT CHK_ROLE_CAN_EDIT CHECK (CAN_EDIT IN (0, 1));
ALTER TABLE APP_ROLE ADD CONSTRAINT CHK_ROLE_CAN_VIEW CHECK (CAN_VIEW IN (0, 1));
ALTER TABLE APP_ROLE ADD CONSTRAINT CHK_ROLE_CAN_DELETE CHECK (CAN_DELETE IN (0, 1));
ALTER TABLE APP_ROLE ADD CONSTRAINT CHK_ROLE_CAN_DOWNLOAD CHECK (CAN_DOWNLOAD IN (0, 1));
ALTER TABLE APP_ROLE ADD CONSTRAINT CHK_ROLE_IS_DELETE CHECK (IS_DELETE IN (0, 1));

ALTER TABLE APP_USER ADD CONSTRAINT CHK_USER_IS_DELETE CHECK (IS_DELETE IN (0, 1));
ALTER TABLE APP_ACCOUNT ADD CONSTRAINT CHK_ACC_IS_DELETE CHECK (IS_DELETE IN (0, 1));

ALTER TABLE LOAI_NHAN_VIEN ADD CONSTRAINT CHK_LNV_MUCLUONG CHECK (MUCLUONG >= 0);
ALTER TABLE LOAIKHUVUC ADD CONSTRAINT CHK_LKV_SOLUONG CHECK (SOLUONG >= 0);
ALTER TABLE LOAIKHUVUC ADD CONSTRAINT CHK_LKV_GIA CHECK (GIA >= 0);

ALTER TABLE QUA_TANG ADD CONSTRAINT CHK_QT_SODIEMTIEUHAO CHECK (SODIEMTIEUHAO > 0);
ALTER TABLE CA_LAM ADD CONSTRAINT CHK_CA_SOGIOLAM CHECK (SOGIOLAM >= 0);
ALTER TABLE CA_LAM ADD CONSTRAINT CHK_CA_TGTANGCA CHECK (THOIGIANTANGCA >= 0);

ALTER TABLE CHUONG_TRINH_KHUYEN_MAI ADD CONSTRAINT CHK_CTKM_CHIETKHAU CHECK (CHIETKHAU >= 0 AND CHIETKHAU <= 100);

ALTER TABLE SAN_PHAM ADD CONSTRAINT CHK_SP_SOLUONGTK CHECK (SOLUONGTK >= 0);
ALTER TABLE SAN_PHAM ADD CONSTRAINT CHK_SP_DONGIABQ CHECK (DONGIABQ >= 0);
ALTER TABLE SAN_PHAM ADD CONSTRAINT CHK_SP_DIEM CHECK (SODIEMTICHLUY >= 0);

ALTER TABLE KHACHHANG ADD CONSTRAINT CHK_KH_DIEM CHECK (SODIEMTICHLUY >= 0);
ALTER TABLE NHAN_VIEN ADD CONSTRAINT CHK_NV_LUONG CHECK (LUONG_CB >= 0);

ALTER TABLE PHIEU_THANH_TOAN ADD CONSTRAINT CHK_PTT_TONGTIEN CHECK (TONGTIEN >= 0);
ALTER TABLE PHIEU_THANH_TOAN ADD CONSTRAINT CHK_PTT_TONGTIENDV CHECK (TONGTIENDV >= 0);
ALTER TABLE PHIEU_THANH_TOAN ADD CONSTRAINT CHK_PTT_TONGTHOIGIAN CHECK (TONGTHOIGIAN >= 0);

ALTER TABLE APP_USER ADD CONSTRAINT CHK_USER_NGAYSINH CHECK (NGAYSINH <= SYSDATE);
ALTER TABLE NHAN_VIEN ADD CONSTRAINT CHK_NV_NGAYVAOLAM CHECK (NGAYVAOLAM <= SYSDATE);


-- ==========================================================
-- RBTV - 2. RÀNG BUỘC LIÊN THUỘC TÍNH (INTRA-RELATION)
-- ==========================================================
ALTER TABLE CA_LAM ADD CONSTRAINT CHK_CA_THOIGIAN CHECK (TGBD < TGKT);
ALTER TABLE CHUONG_TRINH_KHUYEN_MAI ADD CONSTRAINT CHK_CTKM_NGAY CHECK (NGBD <= NGKT);
ALTER TABLE LICHSUCHOI ADD CONSTRAINT CHK_LSC_THOIGIAN CHECK (NGAYBD <= NGAYKT);

-- ==========================================================
-- TRIGGERS
-- ==========================================================
-- R11: Mỗi ca làm có tối đa 5 nhân viên tham gia
CREATE OR REPLACE TRIGGER TRG_R11_MAX_NV_CALAM
BEFORE INSERT OR UPDATE ON CHI_TIET_CA_LAM
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM CHI_TIET_CA_LAM WHERE MACA = :NEW.MACA;
    IF v_count >= 5 THEN
        RAISE_APPLICATION_ERROR(-20011, 'Lỗi (R11): Mỗi ca làm chỉ có tối đa 5 nhân viên tham gia!');
    END IF;
END;
/

-- R16: Ngày nhập kho >= ngày vào làm của nhân viên
CREATE OR REPLACE TRIGGER TRG_R16_NGAYNHAP_NGAYVAOLAM
BEFORE INSERT OR UPDATE ON PHIEU_NHAP_KHO
FOR EACH ROW
DECLARE
    v_ngayvaolam DATE;
BEGIN
    SELECT NGAYVAOLAM INTO v_ngayvaolam FROM NHAN_VIEN WHERE MANV = :NEW.MANV;
    IF :NEW.NGAYNHAP < v_ngayvaolam THEN
        RAISE_APPLICATION_ERROR(-20016, 'Lỗi (R16): Ngày nhập kho phải lớn hơn hoặc bằng ngày vào làm của nhân viên!');
    END IF;
END;
/

-- R17: Mỗi khách hàng đang hoạt động chỉ được đổi tối đa 30 quà tặng
CREATE OR REPLACE TRIGGER TRG_R17_MAX_DOIQUA
BEFORE INSERT OR UPDATE ON LICHSUDOIQUA
FOR EACH ROW
DECLARE
    v_is_delete NUMBER;
    v_count NUMBER;
BEGIN
    SELECT IS_DELETE INTO v_is_delete FROM KHACHHANG WHERE MAKH = :NEW.MAKH;
    IF v_is_delete = 0 THEN
        SELECT COUNT(*) INTO v_count FROM LICHSUDOIQUA WHERE MAKH = :NEW.MAKH;
        IF v_count >= 30 THEN 
            RAISE_APPLICATION_ERROR(-20017, 'Lỗi (R17): Khách hàng đang hoạt động chỉ được đổi tối đa 30 lần!');
        END IF;
    END IF;
END;
/

-- R18: Một máy tính đang hoạt động chỉ được gắn tối đa 10 thiết bị
CREATE OR REPLACE TRIGGER TRG_R18_MAX_THIETBI
BEFORE INSERT OR UPDATE ON THIET_BI
FOR EACH ROW
DECLARE
    v_trangthai PC.TRANGTHAI%TYPE;
    v_count NUMBER;
BEGIN
    SELECT TRANGTHAI INTO v_trangthai FROM PC WHERE MAPC = :NEW.MAPC;
    IF UPPER(v_trangthai) = 'HOATDONG' OR UPPER(v_trangthai) = 'HOẠT ĐỘNG' THEN
        SELECT COUNT(*) INTO v_count FROM THIET_BI WHERE MAPC = :NEW.MAPC;
        IF v_count >= 10 THEN
            RAISE_APPLICATION_ERROR(-20018, 'Lỗi (R18): Máy tính đang hoạt động chỉ được gắn tối đa 10 thiết bị!');
        END IF;
    END IF;
END;
/

-- 1. Tự động tính Tổng Tiền Nhập Kho khi thêm Chi tiết nhập kho
CREATE OR REPLACE TRIGGER TRG_TINH_TONGTIEN_NHAPKHO
AFTER INSERT OR UPDATE ON CHI_TIET_NHAP_KHO
FOR EACH ROW
BEGIN
    UPDATE PHIEU_NHAP_KHO
    SET TONGTIENNHAP = NVL(TONGTIENNHAP, 0) + (:NEW.SOLUONGNHAP * :NEW.GIANHAP) + NVL(:NEW.CHIPHIKHAC, 0)
    WHERE MAPNK = :NEW.MAPNK;
END;
/

-- 2. Tự động tính Tổng Tiền Dịch Vụ khi khách gọi món
CREATE OR REPLACE TRIGGER TRG_TINH_TIEN_DICHVU
AFTER INSERT OR UPDATE ON DICH_VU_DA_DUNG
FOR EACH ROW
DECLARE
    v_dongia SAN_PHAM.DONGIABQ%TYPE;
BEGIN
    SELECT DONGIABQ INTO v_dongia FROM SAN_PHAM WHERE MASP = :NEW.MASP;
    
    UPDATE PHIEU_THANH_TOAN
    SET TONGSODV = NVL(TONGSODV, 0) + :NEW.SL,
        TONGTIENDV = NVL(TONGTIENDV, 0) + (:NEW.SL * v_dongia),
        TONGTIEN = NVL(TONGTIEN, 0) + (:NEW.SL * v_dongia)
    WHERE MALS = :NEW.MALS;
END;
/

-- 3. Đảm bảo Số máy của khu vực khớp với số lượng PC thực tế
CREATE OR REPLACE TRIGGER TRG_CAPNHAT_SOMAY_KHUVUC
AFTER INSERT OR DELETE ON PC
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE KHUVUC SET SOMAYKV = NVL(SOMAYKV, 0) + 1 WHERE MAKV = :NEW.MAKV;
    ELSIF DELETING THEN
        UPDATE KHUVUC SET SOMAYKV = SOMAYKV - 1 WHERE MAKV = :OLD.MAKV;
    END IF;
END;
/

-- 4. Trigger cập nhật tồn kho khi nhập hàng
CREATE OR REPLACE TRIGGER trg_CapNhatTonKho_NhapHang
AFTER INSERT ON CHI_TIET_NHAP_KHO
FOR EACH ROW
DECLARE
    v_soluongtk_hientai SAN_PHAM.SOLUONGTK%TYPE;
    v_tensp             SAN_PHAM.TENSP%TYPE;
BEGIN
    SELECT SOLUONGTK, TENSP 
    INTO v_soluongtk_hientai, v_tensp
    FROM SAN_PHAM
    WHERE MASP = :NEW.MASP;

    IF :NEW.SOLUONGNHAP <= 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 
            'Loi: So luong nhap cho san pham [' || v_tensp || '] phai lon hon 0! ' ||
            '(So luong nhap hien tai: ' || :NEW.SOLUONGNHAP || ')');
    END IF;

    UPDATE SAN_PHAM
    SET SOLUONGTK = v_soluongtk_hientai + :NEW.SOLUONGNHAP
    WHERE MASP = :NEW.MASP;
END;
/

-- 5. Trigger trừ tồn kho khi bán hàng
CREATE OR REPLACE TRIGGER trg_CapNhatTonKho_BanHang
AFTER INSERT ON DICH_VU_DA_DUNG
FOR EACH ROW
DECLARE
    v_soluongtk SAN_PHAM.SOLUONGTK%TYPE;
BEGIN
    SELECT SOLUONGTK INTO v_soluongtk 
    FROM SAN_PHAM 
    WHERE MASP = :NEW.MASP;

    IF v_soluongtk < :NEW.SL THEN
        RAISE_APPLICATION_ERROR(-20002, 'Lỗi: Số lượng tồn kho không đủ để đáp ứng yêu cầu!');
    ELSE
        UPDATE SAN_PHAM
        SET SOLUONGTK = SOLUONGTK - :NEW.SL
        WHERE MASP = :NEW.MASP;
    END IF;
END;
/

-- 6. Trigger cộng điểm tích lũy khi thanh toán
CREATE OR REPLACE TRIGGER trg_CapNhatDiem_ThanhToan
AFTER INSERT ON PHIEU_THANH_TOAN
FOR EACH ROW
DECLARE
    v_makh KHACHHANG.MAKH%TYPE;
BEGIN
    BEGIN
        SELECT MAKH INTO v_makh
        FROM LICHSUCHOI
        WHERE MALS = :NEW.MALS;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_makh := NULL; 
    END;

    IF v_makh IS NOT NULL THEN
        UPDATE KHACHHANG
        SET SODIEMTICHLUY = NVL(SODIEMTICHLUY, 0) + FLOOR(NVL(:NEW.TONGTIEN, 0) / 1000)
        WHERE MAKH = v_makh;
    END IF;
END;
/

-- 7. Trigger trừ điểm khi đổi quà
CREATE OR REPLACE TRIGGER trg_TruDiem_DoiQua
AFTER INSERT ON LICHSUDOIQUA
FOR EACH ROW
DECLARE
    v_diemtieuhao QUA_TANG.SODIEMTIEUHAO%TYPE;
    v_diemhientai KHACHHANG.SODIEMTICHLUY%TYPE;
BEGIN
    SELECT SODIEMTIEUHAO INTO v_diemtieuhao 
    FROM QUA_TANG 
    WHERE MAQT = :NEW.MAQT;

    SELECT SODIEMTICHLUY INTO v_diemhientai 
    FROM KHACHHANG 
    WHERE MAKH = :NEW.MAKH;

    IF NVL(v_diemhientai, 0) < (v_diemtieuhao * :NEW.SL) THEN
        RAISE_APPLICATION_ERROR(-20003, 'Lỗi: Khách hàng không đủ điểm tích lũy để đổi quà!');
    ELSE
        UPDATE KHACHHANG
        SET SODIEMTICHLUY = SODIEMTICHLUY - (v_diemtieuhao * :NEW.SL)
        WHERE MAKH = :NEW.MAKH;
    END IF;
END;
/

-- 8. Trigger cập nhật trạng thái thiết bị khi thay thế
CREATE OR REPLACE TRIGGER trg_CapNhatTrangThai_ThayTheThietBi
AFTER INSERT ON THAYTHETHIETBI
FOR EACH ROW
BEGIN
    UPDATE THIET_BI
    SET TRANGTHAI = 'Hong/Da thao'
    WHERE MATB = :NEW.MATB;
END;
/

-- ==========================================================
--  FUNCTIONS 
-- ==========================================================
CREATE OR REPLACE FUNCTION F_CALC_TEMP_FEE(
    PAR_MALS IN LICHSUCHOI.MALS%TYPE
) RETURN NUMBER
IS
    V_NgayBD       LICHSUCHOI.NGAYBD%TYPE;
    V_MaPC         LICHSUCHOI.MAPC%TYPE;
    V_DonGia       LOAIKHUVUC.GIA%TYPE;
    V_ThoiGianChoi NUMBER;
    V_TienTamTinh  NUMBER := 0;
BEGIN
    SELECT NGAYBD, MAPC INTO V_NgayBD, V_MaPC
    FROM LICHSUCHOI
    WHERE MALS = PAR_MALS AND IS_DELETE = 0;
 
    SELECT LKV.GIA INTO V_DonGia
    FROM PC P
    JOIN KHUVUC KV ON P.MAKV = KV.MAKV
    JOIN LOAIKHUVUC LKV ON KV.MALOAIKV = LKV.MALOAIKV
    WHERE P.MAPC = V_MaPC
      AND P.IS_DELETE = 0 
      AND KV.IS_DELETE = 0 
      AND LKV.IS_DELETE = 0;
 
    V_ThoiGianChoi := ROUND((CAST(SYSTIMESTAMP AS DATE) - CAST(V_NgayBD AS DATE)) * 24 * 60);
 
    IF V_ThoiGianChoi > 0 THEN
        V_TienTamTinh := ROUND((V_ThoiGianChoi / 60) * V_DonGia);
    END IF;
 
    RETURN V_TienTamTinh;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RETURN -1;
END F_CALC_TEMP_FEE;
/

CREATE OR REPLACE FUNCTION F_CALC_TOTAL_REVENUE(
    PAR_MONTH IN NUMBER,
    PAR_YEAR IN NUMBER
) RETURN NUMBER
IS
    V_TotalRevenue NUMBER := 0;
BEGIN
    SELECT NVL(SUM(TONGTIEN), 0) INTO V_TotalRevenue
    FROM PHIEU_THANH_TOAN
    WHERE EXTRACT(MONTH FROM CREATE_AT) = PAR_MONTH
      AND EXTRACT(YEAR FROM CREATE_AT) = PAR_YEAR
      AND (TRANGTHAI = 'Da thanh toan' OR TRANGTHAI = 'Đã thu tiền') 
      AND IS_DELETE = 0;

    RETURN V_TotalRevenue;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RETURN -1;
END F_CALC_TOTAL_REVENUE;
/

CREATE OR REPLACE FUNCTION F_CHECK_PC_STATUS(
    PAR_MAPC IN PC.MAPC%TYPE
) RETURN VARCHAR2
IS
    V_Status PC.TRANGTHAI%TYPE;
BEGIN
    SELECT TRANGTHAI INTO V_Status
    FROM PC
    WHERE MAPC = PAR_MAPC 
      AND IS_DELETE = 0;

    RETURN V_Status;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Không tìm thấy máy';
    WHEN OTHERS THEN
        RETURN 'Lỗi hệ thống';
END F_CHECK_PC_STATUS;
/

CREATE OR REPLACE FUNCTION F_GET_AVAILABLE_POINTS(
    PAR_MAKH IN KHACHHANG.MAKH%TYPE
) RETURN NUMBER
IS
    V_Points NUMBER := 0;
BEGIN
    SELECT SODIEMTICHLUY INTO V_Points
    FROM KHACHHANG
    WHERE MAKH = PAR_MAKH 
      AND IS_DELETE = 0;

    RETURN NVL(V_Points, 0);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0; 
    WHEN OTHERS THEN
        RETURN -1;
END F_GET_AVAILABLE_POINTS;
/

CREATE OR REPLACE FUNCTION F_GET_STOCK_PRODUCT(
    PAR_MASP IN SAN_PHAM.MASP%TYPE
) RETURN NUMBER
IS
    V_Stock NUMBER := 0;
BEGIN
    SELECT SOLUONGTK INTO V_Stock
    FROM SAN_PHAM
    WHERE MASP = PAR_MASP 
      AND IS_DELETE = 0;

    RETURN NVL(V_Stock, 0);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0; 
    WHEN OTHERS THEN
        RETURN -1;
END F_GET_STOCK_PRODUCT;
/

-- ==========================================================
-- PROCEDURES 
-- ==========================================================

-- PROCEDURE ĐỘC LẬP GHI LOG (AUTONOMOUS TRANSACTION)
CREATE OR REPLACE PROCEDURE LOG_ERROR (
    P_PROC_NAME IN VARCHAR2,
    P_ERR_CODE IN NUMBER,
    P_ERR_MSG IN VARCHAR2
) AS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO SYSTEM_ERROR_LOG (PROCEDURE_NAME, ERROR_CODE, ERROR_MESSAGE)
    VALUES (P_PROC_NAME, P_ERR_CODE, P_ERR_MSG);
    COMMIT;
END LOG_ERROR;
/

-- 1. INSERT_ROLE
CREATE OR REPLACE PROCEDURE INSERT_ROLE (
    PAR_ROLENAME    IN  VARCHAR2,
    PAR_CANADD      IN  NUMBER,
    PAR_CANEDIT     IN  NUMBER,
    PAR_CANVIEW     IN  NUMBER,
    PAR_CANDELETE   IN  NUMBER,
    PAR_CANDOWNLOAD IN  NUMBER,
    ROLEID_OUT      OUT NUMBER
) AS
BEGIN
    INSERT INTO APP_ROLE (ROLE_NAME, CAN_ADD, CAN_EDIT, CAN_VIEW, CAN_DELETE, CAN_DOWNLOAD, IS_DELETE)
    VALUES (PAR_ROLENAME, PAR_CANADD, PAR_CANEDIT, PAR_CANVIEW, PAR_CANDELETE, PAR_CANDOWNLOAD, 0)
    RETURNING ROLE_ID INTO ROLEID_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END INSERT_ROLE;
/

-- 2. UPDATE_ROLE
CREATE OR REPLACE PROCEDURE UPDATE_ROLE (
    PAR_ROLEID      IN NUMBER,
    PAR_ROLENAME    IN VARCHAR2,
    PAR_CANADD      IN NUMBER,
    PAR_CANEDIT     IN NUMBER,
    PAR_CANVIEW     IN NUMBER,
    PAR_CANDELETE   IN NUMBER,
    PAR_CANDOWNLOAD IN NUMBER
) AS
BEGIN
    UPDATE APP_ROLE
    SET ROLE_NAME   = PAR_ROLENAME,
        CAN_ADD     = PAR_CANADD,
        CAN_EDIT    = PAR_CANEDIT,
        CAN_VIEW    = PAR_CANVIEW,
        CAN_DELETE  = PAR_CANDELETE,
        CAN_DOWNLOAD = PAR_CANDOWNLOAD
    WHERE ROLE_ID = PAR_ROLEID;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END UPDATE_ROLE;
/

-- 3. DELETE_ROLE
CREATE OR REPLACE PROCEDURE DELETE_ROLE (
    PAR_ROLEID IN NUMBER
) AS
BEGIN
    UPDATE APP_ROLE
    SET IS_DELETE = 1
    WHERE ROLE_ID = PAR_ROLEID;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END DELETE_ROLE;
/

-- 4. INSERT_USER_ACCOUNT
CREATE OR REPLACE PROCEDURE INSERT_USER_ACCOUNT (
    PAR_USERID   IN  VARCHAR2,
    PAR_HOTEN    IN  VARCHAR2,
    PAR_NGAYSINH IN  DATE,
    PAR_SDT      IN  VARCHAR2,
    PAR_DIACHI   IN  VARCHAR2,
    PAR_USERNAME IN  VARCHAR2,
    PAR_PASS     IN  VARCHAR2,
    PAR_ROLEID   IN  NUMBER,
    ACCOUNTID_OUT OUT VARCHAR2
) AS
    V_ACCOUNTID VARCHAR2(50);
BEGIN
    V_ACCOUNTID := 'ACC' || TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MISSFF3');
    ACCOUNTID_OUT := V_ACCOUNTID;

    INSERT INTO APP_USER (USER_ID, HOTEN, NGAYSINH, SDT, DIACHI, IS_DELETE)
    VALUES (PAR_USERID, PAR_HOTEN, PAR_NGAYSINH, PAR_SDT, PAR_DIACHI, 0);

    INSERT INTO APP_ACCOUNT (ACCOUNT_ID, USER_ID, USERNAME, PASS, TRANGTHAI, IS_DELETE)
    VALUES (V_ACCOUNTID, PAR_USERID, PAR_USERNAME, PAR_PASS, 'ACTIVE', 0);

    INSERT INTO ACCOUNT_ROLE (ACCOUNT_ID, ROLE_ID, IS_DELETE)
    VALUES (V_ACCOUNTID, PAR_ROLEID, 0);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END INSERT_USER_ACCOUNT;
/

-- 5. UPDATE_PASSWORD
CREATE OR REPLACE PROCEDURE UPDATE_PASSWORD (
    PAR_ACCOUNTID IN  VARCHAR2,
    PAR_OLDPASS   IN  VARCHAR2,
    PAR_NEWPASS   IN  VARCHAR2,
    STATUS_OUT    OUT NUMBER
) AS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT
    FROM APP_ACCOUNT
    WHERE ACCOUNT_ID = PAR_ACCOUNTID
      AND PASS = PAR_OLDPASS
      AND IS_DELETE = 0;

    IF V_COUNT > 0 THEN
        UPDATE APP_ACCOUNT
        SET PASS = PAR_NEWPASS
        WHERE ACCOUNT_ID = PAR_ACCOUNTID;
        STATUS_OUT := 1;
        COMMIT;
    ELSE
        STATUS_OUT := 0;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END UPDATE_PASSWORD;
/

-- 6. DELETE_USER_ACCOUNT
CREATE OR REPLACE PROCEDURE DELETE_USER_ACCOUNT (
    PAR_USERID IN VARCHAR2
) AS
BEGIN
    UPDATE APP_USER
    SET IS_DELETE = 1
    WHERE USER_ID = PAR_USERID;

    UPDATE APP_ACCOUNT
    SET IS_DELETE = 1
    WHERE USER_ID = PAR_USERID;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END DELETE_USER_ACCOUNT;
/

-- 7. INSERT_NHANVIEN
CREATE OR REPLACE PROCEDURE INSERT_NHANVIEN (
    PAR_MANV       IN VARCHAR2,
    PAR_USERID     IN VARCHAR2,
    PAR_MALNV      IN VARCHAR2,
    PAR_LUONGCB    IN NUMBER,
    PAR_NGAYVAOLAM IN DATE,
    PAR_TRANGTHAI  IN VARCHAR2
) AS
BEGIN
    INSERT INTO NHAN_VIEN (MANV, USER_ID, MALNV, LUONG_CB, NGAYVAOLAM, TRANGTHAI, IS_DELETE)
    VALUES (PAR_MANV, PAR_USERID, PAR_MALNV, PAR_LUONGCB, PAR_NGAYVAOLAM, PAR_TRANGTHAI, 0);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END INSERT_NHANVIEN;
/

-- 8. UPDATE_TRANGTHAI_NV
CREATE OR REPLACE PROCEDURE UPDATE_TRANGTHAI_NV (
    PAR_MANV      IN VARCHAR2,
    PAR_TRANGTHAI IN VARCHAR2
) AS
BEGIN
    UPDATE NHAN_VIEN
    SET TRANGTHAI = PAR_TRANGTHAI
    WHERE MANV = PAR_MANV;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END UPDATE_TRANGTHAI_NV;
/

-- 9. GHI_NHAN_CHAM_CONG
CREATE OR REPLACE PROCEDURE GHI_NHAN_CHAM_CONG (
    PAR_MANV      IN VARCHAR2,
    PAR_MACA      IN VARCHAR2,
    PAR_TRANGTHAI IN VARCHAR2
) AS
BEGIN
    MERGE INTO CHI_TIET_CA_LAM TGT
    USING (SELECT PAR_MANV AS MANV, PAR_MACA AS MACA FROM DUAL) SRC
    ON (TGT.MANV = SRC.MANV AND TGT.MACA = SRC.MACA)
    WHEN MATCHED THEN
        UPDATE SET TGT.TRANGTHAI = PAR_TRANGTHAI
    WHEN NOT MATCHED THEN
        INSERT (MANV, MACA, TRANGTHAI)
        VALUES (PAR_MANV, PAR_MACA, PAR_TRANGTHAI);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END GHI_NHAN_CHAM_CONG;
/

-- 10. DELETE_NHANVIEN
CREATE OR REPLACE PROCEDURE DELETE_NHANVIEN (
    PAR_MANV IN VARCHAR2
) AS
BEGIN
    UPDATE NHAN_VIEN
    SET IS_DELETE = 1
    WHERE MANV = PAR_MANV;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END DELETE_NHANVIEN;
/

-- 11. INSERT_KHACHHANG
CREATE OR REPLACE PROCEDURE INSERT_KHACHHANG (
    PAR_MAKH   IN VARCHAR2,
    PAR_USERID IN VARCHAR2,
    PAR_SODT   IN VARCHAR2
) AS
BEGIN
    INSERT INTO KHACHHANG (MAKH, USER_ID, SODT, SODIEMTICHLUY, SODU, IS_DELETE)
    VALUES (PAR_MAKH, PAR_USERID, PAR_SODT, 0, 0, 0);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END INSERT_KHACHHANG;
/

-- 12. UPDATE_DIEM_KH
CREATE OR REPLACE PROCEDURE UPDATE_DIEM_KH (
    PAR_MAKH         IN VARCHAR2,
    PAR_DIEMCONGTHEM IN NUMBER
) AS
BEGIN
    UPDATE KHACHHANG
    SET SODIEMTICHLUY = SODIEMTICHLUY + PAR_DIEMCONGTHEM
    WHERE MAKH = PAR_MAKH;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END UPDATE_DIEM_KH;
/

-- 13. INSERT_DOIQUA
CREATE OR REPLACE PROCEDURE INSERT_DOIQUA (
    PAR_MADQ IN VARCHAR2,
    PAR_MAKH IN VARCHAR2,
    PAR_MAQT IN VARCHAR2,
    PAR_SL   IN NUMBER
) AS
    V_DIEMDOI   NUMBER;
    V_TONGDIEM  NUMBER;
    V_HIENTAI   NUMBER;
BEGIN
    SELECT SODIEMTIEUHAO INTO V_DIEMDOI
    FROM QUA_TANG
    WHERE MAQT = PAR_MAQT AND IS_DELETE = 0;

    V_TONGDIEM := V_DIEMDOI * PAR_SL;

    SELECT SODIEMTICHLUY INTO V_HIENTAI
    FROM KHACHHANG
    WHERE MAKH = PAR_MAKH;

    IF V_HIENTAI < V_TONGDIEM THEN
        RAISE_APPLICATION_ERROR(-20001, 'Khách hàng không đủ điểm để đổi quà.');
    END IF;

    INSERT INTO LICHSUDOIQUA (MADQ, MAKH, MAQT, SL, TRANGTHAI, IS_DELETE)
    VALUES (PAR_MADQ, PAR_MAKH, PAR_MAQT, PAR_SL, 'THANH_CONG', 0);

    UPDATE KHACHHANG
    SET SODIEMTICHLUY = SODIEMTICHLUY - V_TONGDIEM
    WHERE MAKH = PAR_MAKH;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END INSERT_DOIQUA;
/

-- 14. INSERT_KHUYENMAI
CREATE OR REPLACE PROCEDURE INSERT_KHUYENMAI (
    PAR_MACTR     IN VARCHAR2,
    PAR_TENCTR    IN VARCHAR2,
    PAR_NGBD      IN DATE,
    PAR_NGKT      IN DATE,
    PAR_CHIETKHAU IN NUMBER,
    PAR_LOAICTR   IN VARCHAR2
) AS
BEGIN
    INSERT INTO CHUONG_TRINH_KHUYEN_MAI (MACTR, TENCTR, NGBD, NGKT, CHIETKHAU, LOAICTR, IS_DELETE)
    VALUES (PAR_MACTR, PAR_TENCTR, PAR_NGBD, PAR_NGKT, PAR_CHIETKHAU, PAR_LOAICTR, 0);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END INSERT_KHUYENMAI;
/

-- 15. APPLY_KHUYENMAI_SP
CREATE OR REPLACE PROCEDURE APPLY_KHUYENMAI_SP (
    PAR_MAKMSP IN VARCHAR2,
    PAR_MASP   IN VARCHAR2,
    PAR_MACTR  IN VARCHAR2
) AS
BEGIN
    INSERT INTO KHUYEN_MAI_SAN_PHAM (MAKMSP, MASP, MACTR, IS_DELETE)
    VALUES (PAR_MAKMSP, PAR_MASP, PAR_MACTR, 0);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END APPLY_KHUYENMAI_SP;
/

-- 16. DELETE_KHACHHANG
CREATE OR REPLACE PROCEDURE DELETE_KHACHHANG (
    PAR_MAKH IN VARCHAR2
) AS
BEGIN
    UPDATE KHACHHANG
    SET IS_DELETE = 1
    WHERE MAKH = PAR_MAKH;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END DELETE_KHACHHANG;
/

-- 17. DELETE_KHUYENMAI
CREATE OR REPLACE PROCEDURE DELETE_KHUYENMAI (
    PAR_MACTR IN VARCHAR2
) AS
BEGIN
    UPDATE CHUONG_TRINH_KHUYEN_MAI
    SET IS_DELETE = 1
    WHERE MACTR = PAR_MACTR;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END DELETE_KHUYENMAI;
/

-- 18. INSERT_PC
CREATE OR REPLACE PROCEDURE INSERT_PC (
    PAR_MAPC      IN VARCHAR2,
    PAR_MAKV      IN VARCHAR2,
    PAR_CPU       IN VARCHAR2,
    PAR_RAM       IN VARCHAR2,
    PAR_VGA       IN VARCHAR2,
    PAR_ROM       IN VARCHAR2,
    PAR_SOMAY     IN NUMBER,
    PAR_LOAIPC    IN VARCHAR2,
    PAR_TRANGTHAI IN VARCHAR2
) AS
BEGIN
    INSERT INTO PC (MAPC, MAKV, CPU, RAM, VGA, ROM, SOMAY, LOAIPC, TRANGTHAI, IS_DELETE)
    VALUES (PAR_MAPC, PAR_MAKV, PAR_CPU, PAR_RAM, PAR_VGA, PAR_ROM, PAR_SOMAY, PAR_LOAIPC, PAR_TRANGTHAI, 0);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END INSERT_PC;
/

-- 19. UPDATE_STATUS_PC
CREATE OR REPLACE PROCEDURE UPDATE_STATUS_PC (
    PAR_MAPC      IN VARCHAR2,
    PAR_TRANGTHAI IN VARCHAR2
) AS
BEGIN
    UPDATE PC
    SET TRANGTHAI = PAR_TRANGTHAI
    WHERE MAPC = PAR_MAPC;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END UPDATE_STATUS_PC;
/

-- 20. INSERT_THIETBI
CREATE OR REPLACE PROCEDURE INSERT_THIETBI (
    PAR_MATB      IN VARCHAR2,
    PAR_MAPC      IN VARCHAR2,
    PAR_TENTB     IN VARCHAR2,
    PAR_LOAITB    IN VARCHAR2,
    PAR_TRANGTHAI IN VARCHAR2
) AS
BEGIN
    INSERT INTO THIET_BI (MATB, MAPC, TENTB, LOAITB, TRANGTHAI, IS_DELETE)
    VALUES (PAR_MATB, PAR_MAPC, PAR_TENTB, PAR_LOAITB, PAR_TRANGTHAI, 0);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END INSERT_THIETBI;
/

-- 21. INSERT_THAY_THE_THIETBI
CREATE OR REPLACE PROCEDURE INSERT_THAY_THE_THIETBI (
    PAR_MATTTB    IN VARCHAR2,
    PAR_MATB      IN VARCHAR2,
    PAR_MAPC      IN VARCHAR2,
    PAR_MANV      IN VARCHAR2,
    PAR_TRANGTHAI IN VARCHAR2
) AS
BEGIN
    INSERT INTO THAYTHETHIETBI (MATTTB, MATB, MAPC, MANV, TRANGTHAI, IS_DELETE)
    VALUES (PAR_MATTTB, PAR_MATB, PAR_MAPC, PAR_MANV, PAR_TRANGTHAI, 0);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END INSERT_THAY_THE_THIETBI;
/

-- 22. DELETE_PC
CREATE OR REPLACE PROCEDURE DELETE_PC (
    PAR_MAPC IN VARCHAR2
) AS
BEGIN
    UPDATE PC
    SET IS_DELETE = 1
    WHERE MAPC = PAR_MAPC;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END DELETE_PC;
/

-- 23. DELETE_THIETBI
CREATE OR REPLACE PROCEDURE DELETE_THIETBI (
    PAR_MATB IN VARCHAR2
) AS
BEGIN
    UPDATE THIET_BI
    SET IS_DELETE = 1
    WHERE MATB = PAR_MATB;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END DELETE_THIETBI;
/

-- 24. START_SESSION_PC
CREATE OR REPLACE PROCEDURE START_SESSION_PC (
    PAR_MAPC IN  VARCHAR2,
    PAR_MAKH IN  VARCHAR2,
    MALS_OUT OUT VARCHAR2
) AS
BEGIN
    MALS_OUT := 'LS' || TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MISSFF3');

    INSERT INTO LICHSUCHOI (MALS, MAPC, MAKH, NGAYBD, TRANGTHAI, IS_DELETE)
    VALUES (MALS_OUT, PAR_MAPC, PAR_MAKH, SYSTIMESTAMP, 'DANGCHOI', 0);

    UPDATE PC
    SET TRANGTHAI = 'DANGDUNG'
    WHERE MAPC = PAR_MAPC;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END START_SESSION_PC;
/

-- 25. END_SESSION_PC
CREATE OR REPLACE PROCEDURE END_SESSION_PC (
    PAR_MALS        IN  VARCHAR2,
    THOIGIAN_OUT    OUT NUMBER,
    TIENTAMTINH_OUT OUT NUMBER
) AS
    V_MAPC       VARCHAR2(50);
    V_NGAYBD     TIMESTAMP;
    V_GIA        NUMBER;
BEGIN
    SELECT MAPC, NGAYBD INTO V_MAPC, V_NGAYBD
    FROM LICHSUCHOI
    WHERE MALS = PAR_MALS;

    THOIGIAN_OUT := ROUND((CAST(SYSTIMESTAMP AS DATE) - CAST(V_NGAYBD AS DATE)) * 24 * 60);

    SELECT LKV.GIA INTO V_GIA
    FROM PC P
    JOIN KHUVUC KV   ON P.MAKV     = KV.MAKV
    JOIN LOAIKHUVUC LKV ON KV.MALOAIKV = LKV.MALOAIKV
    WHERE P.MAPC = V_MAPC;

    TIENTAMTINH_OUT := ROUND(THOIGIAN_OUT / 60 * V_GIA);

    UPDATE LICHSUCHOI
    SET NGAYKT    = SYSTIMESTAMP,
        TRANGTHAI = 'DAKET'
    WHERE MALS = PAR_MALS;

    UPDATE PC
    SET TRANGTHAI = 'TRONG'
    WHERE MAPC = V_MAPC;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END END_SESSION_PC;
/

-- 26. ORDER_DICHVU
CREATE OR REPLACE PROCEDURE ORDER_DICHVU (
    PAR_MADVDD IN VARCHAR2,
    PAR_MALS   IN VARCHAR2,
    PAR_MASP   IN VARCHAR2,
    PAR_SL     IN NUMBER
) AS
BEGIN
    INSERT INTO DICH_VU_DA_DUNG (MADVDD, MALS, MASP, SL, TRANGTHAI, IS_DELETE)
    VALUES (PAR_MADVDD, PAR_MALS, PAR_MASP, PAR_SL, 'DAXULY', 0);

    UPDATE_TONKHO(PAR_MASP, -PAR_SL);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END ORDER_DICHVU;
/

-- 27. DELETE_ORDER_DICHVU
CREATE OR REPLACE PROCEDURE DELETE_ORDER_DICHVU (
    PAR_MADVDD IN VARCHAR2
) AS
    V_MASP VARCHAR2(50);
    V_SL   NUMBER;
BEGIN
    SELECT MASP, SL INTO V_MASP, V_SL
    FROM DICH_VU_DA_DUNG
    WHERE MADVDD = PAR_MADVDD AND IS_DELETE = 0;

    UPDATE DICH_VU_DA_DUNG
    SET IS_DELETE = 1
    WHERE MADVDD = PAR_MADVDD;

    UPDATE_TONKHO(V_MASP, V_SL);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END DELETE_ORDER_DICHVU;
/

-- 28. CREATE_THANHTOAN
CREATE OR REPLACE PROCEDURE CREATE_THANHTOAN(
    PAR_MAPTT       IN PHIEU_THANH_TOAN.MAPTT%TYPE,
    PAR_MALS        IN PHIEU_THANH_TOAN.MALS%TYPE,
    PAR_TRANGTHAI   IN PHIEU_THANH_TOAN.TRANGTHAI%TYPE,
    TONGTIEN_OUT    OUT PHIEU_THANH_TOAN.TONGTIEN%TYPE,
    TONGTHOIGIAN_OUT OUT PHIEU_THANH_TOAN.TONGTHOIGIAN%TYPE,
    TONGSODV_OUT    OUT PHIEU_THANH_TOAN.TONGSODV%TYPE,
    TONGTIENDV_OUT  OUT PHIEU_THANH_TOAN.TONGTIENDV%TYPE
)
IS
    V_CountLS      NUMBER;
    V_CountPTT     NUMBER;
    V_NgayBD       LICHSUCHOI.NGAYBD%TYPE;
    V_NgayKT       LICHSUCHOI.NGAYKT%TYPE;
    V_MaPC         LICHSUCHOI.MAPC%TYPE;
    V_DonGia       LOAIKHUVUC.GIA%TYPE;
    V_TienGio      NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO V_CountLS FROM LICHSUCHOI WHERE MALS = PAR_MALS;

    IF V_CountLS = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Lỗi: Không tồn tại phiên chơi này trong hệ thống!');
    END IF;

    SELECT COUNT(*) INTO V_CountPTT FROM PHIEU_THANH_TOAN WHERE MALS = PAR_MALS AND TRANGTHAI = 'Đã thanh toán' AND IS_DELETE = 0;

    IF V_CountPTT > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Lỗi: Phiên chơi này đã được thanh toán trước đó!');
    END IF;

    SELECT NGAYBD, NGAYKT, MAPC INTO V_NgayBD, V_NgayKT, V_MaPC FROM LICHSUCHOI WHERE MALS = PAR_MALS;

    IF V_NgayKT IS NULL THEN
        RAISE_APPLICATION_ERROR(-20003, 'Lỗi: Phiên chơi chưa kết thúc (Chưa đóng máy)!');
    END IF;

    TONGTHOIGIAN_OUT := ROUND((CAST(V_NgayKT AS DATE) - CAST(V_NgayBD AS DATE)) * 24 * 60);

    SELECT LKV.GIA INTO V_DonGia
    FROM PC P JOIN KHUVUC KV ON P.MAKV = KV.MAKV JOIN LOAIKHUVUC LKV ON KV.MALOAIKV = LKV.MALOAIKV
    WHERE P.MAPC = V_MaPC;

    V_TienGio := ROUND((TONGTHOIGIAN_OUT / 60) * V_DonGia);

    SELECT NVL(SUM(DV.SL), 0), NVL(SUM(DV.SL * SP.DONGIABQ), 0)
    INTO TONGSODV_OUT, TONGTIENDV_OUT
    FROM DICH_VU_DA_DUNG DV JOIN SAN_PHAM SP ON DV.MASP = SP.MASP
    WHERE DV.MALS = PAR_MALS AND DV.TRANGTHAI <> 'Đã hủy';

    TONGTIEN_OUT := V_TienGio + TONGTIENDV_OUT;

    INSERT INTO PHIEU_THANH_TOAN (
        MAPTT, MALS, TONGTIEN, TONGTHOIGIAN, TONGSODV, TONGTIENDV, TRANGTHAI, IS_DELETE, CREATE_AT
    )
    VALUES (
        PAR_MAPTT, PAR_MALS, TONGTIEN_OUT, TONGTHOIGIAN_OUT, TONGSODV_OUT, TONGTIENDV_OUT, PAR_TRANGTHAI, 0, CURRENT_TIMESTAMP
    );

    UPDATE PC SET TRANGTHAI = 'TRONG' WHERE MAPC = V_MaPC;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20004, 'Lỗi: Không tìm thấy dữ liệu hợp lệ để xử lý thanh toán!');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END CREATE_THANHTOAN;
/

-- 29. INSERT_SANPHAM
CREATE OR REPLACE PROCEDURE INSERT_SANPHAM (
    PAR_MASP          IN VARCHAR2,
    PAR_TENSP         IN VARCHAR2,
    PAR_DVT           IN VARCHAR2,
    PAR_LOAISP        IN VARCHAR2,
    PAR_DONGIABQ      IN NUMBER,
    PAR_SODIEMTICHLUY IN NUMBER
) AS
BEGIN
    INSERT INTO SAN_PHAM (MASP, TENSP, DVT, LOAISP, DONGIABQ, SODIEMTICHLUY, SOLUONGTK, IS_DELETE)
    VALUES (PAR_MASP, PAR_TENSP, PAR_DVT, PAR_LOAISP, PAR_DONGIABQ, PAR_SODIEMTICHLUY, 0, 0);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END INSERT_SANPHAM;
/

-- 30. CREATE_PHIEUNHAP
CREATE OR REPLACE PROCEDURE CREATE_PHIEUNHAP (
    PAR_MAKHO IN  VARCHAR2,
    PAR_MANV  IN  VARCHAR2,
    MAPNK_OUT OUT VARCHAR2
) AS
BEGIN
    MAPNK_OUT := 'PN' || TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MISSFF3');

    INSERT INTO PHIEU_NHAP_KHO (MAPNK, MAKHO, MANV, NGAYNHAP, TONGTIENNHAP)
    VALUES (MAPNK_OUT, PAR_MAKHO, PAR_MANV, SYSDATE, 0);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END CREATE_PHIEUNHAP;
/

-- 31. INSERT_CT_NHAPKHO (CÓ SỬ DỤNG SAVEPOINT)
CREATE OR REPLACE PROCEDURE INSERT_CT_NHAPKHO (
    PAR_MAPNK       IN VARCHAR2,
    PAR_MASP        IN VARCHAR2,
    PAR_LOAIHANG    IN VARCHAR2,
    PAR_SOLUONGNHAP IN NUMBER,
    PAR_GIANHAP     IN NUMBER,
    PAR_CHIPHIKHAC  IN NUMBER
) AS
    V_THANHTIEN NUMBER;
BEGIN
    SAVEPOINT truoc_khi_nhap_ct;

    V_THANHTIEN := PAR_SOLUONGNHAP * PAR_GIANHAP + NVL(PAR_CHIPHIKHAC, 0);

    INSERT INTO CHI_TIET_NHAP_KHO (MAPNK, MASP, LOAIHANG, SOLUONGNHAP, GIANHAP)
    VALUES (PAR_MAPNK, PAR_MASP, PAR_LOAIHANG, PAR_SOLUONGNHAP, PAR_GIANHAP);

    UPDATE PHIEU_NHAP_KHO
    SET TONGTIENNHAP = TONGTIENNHAP + V_THANHTIEN
    WHERE MAPNK = PAR_MAPNK;

    UPDATE_TONKHO(PAR_MASP, PAR_SOLUONGNHAP);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO truoc_khi_nhap_ct;
        LOG_ERROR('INSERT_CT_NHAPKHO', SQLCODE, SQLERRM);
        RAISE;
END INSERT_CT_NHAPKHO;
/

-- 32. UPDATE_TONKHO (Thủ tục nội bộ)
CREATE OR REPLACE PROCEDURE UPDATE_TONKHO (
    PAR_MASP       IN VARCHAR2,
    PAR_SL_THAYDOI IN NUMBER
) AS
BEGIN
    UPDATE SAN_PHAM
    SET SOLUONGTK = SOLUONGTK + PAR_SL_THAYDOI
    WHERE MASP = PAR_MASP;
END UPDATE_TONKHO;
/

-- 33. DELETE_SANPHAM
CREATE OR REPLACE PROCEDURE DELETE_SANPHAM (
    PAR_MASP IN VARCHAR2
) AS
BEGIN
    UPDATE SAN_PHAM
    SET IS_DELETE = 1
    WHERE MASP = PAR_MASP;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END DELETE_SANPHAM;
/

-- INSERT_PHIEU_THANH_TOAN (Phiên bản tách rời)
CREATE OR REPLACE PROCEDURE INSERT_PHIEU_THANH_TOAN (
    PAR_MALS          PHIEU_THANH_TOAN.MALS%TYPE,
    PAR_TONGTIEN      PHIEU_THANH_TOAN.TONGTIEN%TYPE,
    PAR_TONGTHOIGIAN  PHIEU_THANH_TOAN.TONGTHOIGIAN%TYPE,
    PAR_TONGSODV     PHIEU_THANH_TOAN.TONGSODV%TYPE,
    PAR_TONGTIENDV    PHIEU_THANH_TOAN.TONGTIENDV%TYPE,
    PAR_TRANGTHAI     PHIEU_THANH_TOAN.TRANGTHAI%TYPE,
    MAPTT_OUT     OUT PHIEU_THANH_TOAN.MAPTT%TYPE
)
AS
    VAR_NEW_MAPTT VARCHAR2(50);
BEGIN
    VAR_NEW_MAPTT := 'PTT_' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '_' || TO_CHAR(SYS_GUID());

    INSERT INTO PHIEU_THANH_TOAN (MAPTT, MALS, TONGTIEN, TONGTHOIGIAN, TONGSODV, TONGTIENDV, TRANGTHAI)
    VALUES (VAR_NEW_MAPTT, PAR_MALS, PAR_TONGTIEN, PAR_TONGTHOIGIAN, PAR_TONGSODV, PAR_TONGTIENDV, PAR_TRANGTHAI)
    RETURNING MAPTT INTO MAPTT_OUT;

    UPDATE LICHSUCHOI
    SET TRANGTHAI = 'Da thanh toan',
        NGAYKT = CURRENT_TIMESTAMP
    WHERE MALS = PAR_MALS;
    COMMIT;
END;
/

-- INSERT_LICHSUCHOI (Tạo phiên chơi thủ công)
CREATE OR REPLACE PROCEDURE INSERT_LICHSUCHOI (
    PAR_MAPC        LICHSUCHOI.MAPC%TYPE,
    PAR_MAKH        LICHSUCHOI.MAKH%TYPE,
    PAR_TRANGTHAI   LICHSUCHOI.TRANGTHAI%TYPE,
    MALS_OUT    OUT LICHSUCHOI.MALS%TYPE
)
AS
    VAR_NEW_MALS VARCHAR2(50);
BEGIN
    VAR_NEW_MALS := 'LSC_' || TO_CHAR(SYS_GUID());
    INSERT INTO LICHSUCHOI (MALS, MAPC, MAKH, NGAYBD, NGAYKT, TRANGTHAI)
    VALUES (VAR_NEW_MALS, PAR_MAPC, PAR_MAKH, CURRENT_TIMESTAMP, NULL, PAR_TRANGTHAI)
    RETURNING MALS INTO MALS_OUT;
    COMMIT;
END;
/

-- CONG_DIEM_TICHLUY (SERIALIZABLE + ERROR LOG)
CREATE OR REPLACE PROCEDURE CONG_DIEM_TICHLUY (
    PAR_MAKH KHACHHANG.MAKH%TYPE,
    PAR_DIEM_CONG NUMBER
)
AS
    VAR_DIEM_HIENTAI NUMBER;
BEGIN
    COMMIT; 
    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

    SELECT SODIEMTICHLUY INTO VAR_DIEM_HIENTAI
    FROM KHACHHANG
    WHERE MAKH = PAR_MAKH;
    
    DBMS_SESSION.SLEEP(5);    
    
    UPDATE KHACHHANG
    SET SODIEMTICHLUY = VAR_DIEM_HIENTAI + PAR_DIEM_CONG
    WHERE MAKH = PAR_MAKH;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        LOG_ERROR('CONG_DIEM_TICHLUY', SQLCODE, SQLERRM);
        RAISE;
END;
/

-- TRU_DIEM_DOIQUA (SERIALIZABLE + ERROR LOG)
CREATE OR REPLACE PROCEDURE TRU_DIEM_DOIQUA (
    PAR_MAKH KHACHHANG.MAKH%TYPE,
    PAR_DIEM_TRU NUMBER
)
AS
    VAR_DIEM_HIENTAI NUMBER;
BEGIN
    COMMIT;
    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

    SELECT SODIEMTICHLUY INTO VAR_DIEM_HIENTAI
    FROM KHACHHANG
    WHERE MAKH = PAR_MAKH;
    
    UPDATE KHACHHANG
    SET SODIEMTICHLUY = VAR_DIEM_HIENTAI - PAR_DIEM_TRU
    WHERE MAKH = PAR_MAKH;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        LOG_ERROR('TRU_DIEM_DOIQUA_MANUAL', SQLCODE, SQLERRM);
        RAISE;
END;
/

-- THAY_THE_THIET_BI_PC
CREATE OR REPLACE PROCEDURE THAY_THE_THIET_BI_PC (
    PAR_MATB VARCHAR2,
    PAR_MAPC VARCHAR2
) AS
BEGIN
    UPDATE THIET_BI 
    SET TRANGTHAI = 'Da thay the' 
    WHERE MATB = PAR_MATB;
    
    DBMS_SESSION.SLEEP(5); 
    
    UPDATE PC 
    SET TRANGTHAI = 'Hoat dong' 
    WHERE MAPC = PAR_MAPC;
    COMMIT;
END; 
/

-- BAO_TRI_MAY_TRAM
CREATE OR REPLACE PROCEDURE BAO_TRI_MAY_TRAM (
    PAR_MAPC VARCHAR2,
    PAR_MATB VARCHAR2
) AS
BEGIN
    UPDATE PC 
    SET TRANGTHAI = 'Bao tri' 
    WHERE MAPC = PAR_MAPC;
    
    DBMS_SESSION.SLEEP(5);
    
    UPDATE THIET_BI 
    SET TRANGTHAI = 'Bao tri' 
    WHERE MATB = PAR_MATB;
    COMMIT;
END;
/

-- CAPNHAT_GIA_SANPHAM
CREATE OR REPLACE PROCEDURE CAPNHAT_GIA_SANPHAM (
    PAR_MASP VARCHAR2,
    PAR_GIA_MOI NUMBER
) AS
BEGIN
    UPDATE SAN_PHAM
    SET DONGIABQ = PAR_GIA_MOI
    WHERE MASP = PAR_MASP;
    COMMIT;
END;
/


